// <auto-generated />
namespace CarSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _43242 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_43242));
        
        string IMigrationMetadata.Id
        {
            get { return "201810081539020_43242"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
